name: CD

on:
  workflow_call:
    secrets:
      MIDNIGHTCI_PACKAGES_WRITE:
        required: true
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to use"
        required: false
        default: "main"

permissions: {}

jobs:
  publish:
    name: Build packages, push to docker registry and npm registry
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
      packages: write # This is required for using GH docker registry
    # if: ${{ github.event_name != 'schedule' && (github.ref_name == 'main' || contains(github.event.head_commit.message, '[do_publish]') || contains(github.event.ref, 'tags') || github.event_name == 'workflow_dispatch') }}
    steps:
      - name: Checkout midnight-faucet repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: "@midnight-ntwrk"
          node-version-file: ".nvmrc"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Enable Corepack
        run: corepack enable

      - name: Configure yarn
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}"

      - name: Log in to GitHub Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: "https://ghcr.io"
          username: ntwrk-bot
          password: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Docker setup buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
        with:
          platforms: linux/arm64,linux/amd64

      - name: Dependencies cache restore
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ./.yarn/cache
            ./node_modules
          key: yarn-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            yarn-${{ github.ref_name }}
            yarn-main

      - name: Yarn install
        run: "yarn install --immutable"

      - name: Turbo cache restore
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ./turbo_cache
          key: turbo-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            turbo-${{ github.ref_name }}
            turbo-main

      - name: Build
        run: "yarn build --cache-dir ./turbo_cache"

      - name: Temp bump prerelease
        if: ${{!contains(github.event.ref, 'tags') }} # When a tag is created, we want to use the version that is being saved in package.json
        run: yarn version prerelease --immediate

      - name: Calculate versions and tags
        id: vars
        env:
          GIT_SHA: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
          HEAD_REF: ${{ github.head_ref || github.ref_name }}
        run: |
          calculatedSha=$(git rev-parse --short "$GIT_SHA")
          currentVersion=$(jq -r .version package.json)
          targetVersion="$currentVersion-pre.$calculatedSha.$RUN_NUMBER"
          echo "target_version=$targetVersion" >> "$GITHUB_OUTPUT"

          dockerTag=$(echo "$HEAD_REF" | tr '/' '-')
          echo "docker_tag=$dockerTag" >> "$GITHUB_OUTPUT"

      - name: Bump versions
        if: ${{!contains(github.event.ref, 'refs/tags/') }} # When a tag is created, we want to use the version that is being saved in package.json
        env:
          TARGET_VERSION: ${{ steps.vars.outputs.target_version }}
        run: yarn workspaces foreach --all version "$TARGET_VERSION"

      - name: Publish prerelease packages
        if: ${{ !startsWith(github.ref, 'refs/tags/') }} # When a tag is created, we want to use the version that is being saved in package.json
        run: yarn do-publish --cache-dir ./turbo_cache -- --tag prerelease

      - name: Publish release packages
        if: contains(github.event.ref, 'tags') #When a tag is created, we want to use the version that is being saved in package.json
        run: yarn do-publish --cache-dir ./turbo_cache

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          docker system prune -af

      # TODO build and push latest only for builds from main branch
      - name: Create multiplatform image and push
        env:
          DOCKER_TAG: ${{ steps.vars.outputs.docker_tag }}
        run: |
          docker buildx build \
          --platform linux/arm64,linux/amd64 \
          -t "ghcr.io/midnight-ntwrk/midnight-faucet:${DOCKER_TAG}" \
          --push .
