name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    tags:
      - '*'

permissions: {}

jobs:
  check:
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      packages: write
      checks: write
      pull-requests: write
    uses: ./.github/workflows/ci.yml

  publish:
    needs: 'check'
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      packages: write
      checks: write
      pull-requests: write
    uses: ./.github/workflows/cd.yml
