name: Faucet E2E Test - stagenet

on:
  workflow_dispatch:
#   schedule:
#     # Runs daily
#     - cron: "0 5 * * *"

permissions: {}

jobs:
  test:
    name: Faucet E2E Test
    permissions:
      contents: read
      packages: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/e2e-test.yml
    with:
      network: stagenet
    secrets:
      MIDNIGHTCI_PACKAGES_READ: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}
      TURNSTILE_HEADER: ${{ secrets.TURNSTILE_HEADER }}
      VISITOR_PASSWORD: ${{ secrets.VISITOR_PASSWORD }}
