name: Faucet Load Test

permissions: {}

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: Midnight network to use
        required: true
        default: "qanet"
        options:
          - qanet
          - preview
          - preprod
          - stagenet
      numberOfUsers:
        required: true
        default: "1"
      warmupRuns:
        required: true
        default: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
      packages: read # This is required for using GH docker registry
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: "@midnight-ntwrk"
          node-version-file: ".nvmrc"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}

      - name: Log in to GitHub Container registry
        uses: docker/login-action@0a596b2e7a325f0cedf8e9bd21ab002cbd3c9241
        with:
          registry: "https://ghcr.io"
          username: ntwrk-bot
          password: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}

      - name: Configure yarn
        env:
          GH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "$GH_TOKEN"

      - name: Dependencies cache restore
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ./.yarn/cache
            ./node_modules
          key: yarn-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            yarn-${{ github.ref_name }}
            yarn-main

      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn build

      - name: Run Load Test
        env:
          NETWORK: ${{ inputs.network }}
          NUMBER_OF_USERS: ${{ inputs.numberOfUsers }}
          WARMUP_RUNS: ${{ inputs.warmupRuns }}
        run: |
          ./tests/src/load/loadTest.mjs
