name: Faucet Smoke Test - devnet

on:
  workflow_dispatch:
  schedule:
    # Runs twice a day
    - cron: "0 0,6,12,16 * * *"

permissions: {}

jobs:
  test:
    name: Faucet Smoke Test
    permissions:
      contents: read
      packages: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/smoke-test.yml
    with:
      network: devnet
    secrets:
      MIDNIGHTCI_PACKAGES_READ: ${{ secrets.MIDNIGHTCI_PACKAGES_READ }}
      TURNSTILE_HEADER: ${{ secrets.TURNSTILE_HEADER }}
      THIRD_PARTY_API_KEY: ${{ secrets.THIRD_PARTY_API_KEY }}
